Final_Project/Team3_FinalProject/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Team3_FinalProject.DAL;
using Team3_FinalProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Runtime.Intrinsics.Arm;
using Team3_FinalProject.Utilities;
using Team3_FinalProject.SendMail;


namespace Team3_FinalProject.Controllers
{
    [Authorize]
    public class AccountsController : Controller
    {
        private readonly AppDbContext _context;

        public AccountsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Accounts
        public IActionResult Index()
        {
            //Set up a list of accounts to display
            List<Account> accounts;
            if (User.IsInRole("Customer")) //user is a customer, so only display their records
            {
                accounts = _context.Accounts
                                .Include(a => a.Transactions)
                                .ThenInclude(a => a.Disputes)
                                .Include(a => a.AppUser)
                                .Where(a => a.AppUser.UserName == User.Identity.Name)
                                .ToList();
                if (accounts[0].AppUser.Disabled)
                {
                    //add an error to the model to show invalid attempt
                    ModelState.AddModelError("", "Disabled customer can no longer view accounts.");
                    //send user back to login page to try again
                    return RedirectToAction("Index","Account");
                }
            }
            else 
            {
                accounts = _context.Accounts
                                .Include(a => a.Transactions)
                                .ThenInclude(a => a.Disputes)
                                .Include(a => a.AppUser)
                                .ToList();
            }

            //
            return View(accounts);
        }


        // GET: Accounts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Accounts == null)
            {
                return View("Error", new string[] { "Please specify an account to view!" });
            }

            

            var account = await _context.Accounts
                .Include(acc => acc.Transactions)
                .ThenInclude(acc => acc.Disputes)
                .Include(acc => acc.AppUser)
                .FirstOrDefaultAsync(m => m.AccountID == id);
            
            if (account == null)
            {
                return NotFound();
            }
            if (account.Transactions == null)
            {
                return RedirectToAction("Transact", "Transactions", new { accountID = id });
            }
            if (User.IsInRole("Customer") && account.AppUser.UserName != User.Identity.Name)
            {
                return View("Error", new String[] { "You are not authorized to view this account!" });
            }
            if (User.IsInRole("Customer") && !account.Active)
            {
                return View("Error", new String[] { "This account is inactivate right now!" });
            }

            return View(account);
        }

        // GET: Accounts/Apply
        [Authorize(Roles = "Customer")]
        public IActionResult Apply()
        {
            return View();
        }

        // POST: Accounts/Apply
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Apply([Bind("AccountID,AccountType,AccountName")] Account account)
        {
            account.AccountNo = Utilities.GenerateNextAccountNumber.GetNextAccountNumber(_context);
            account.AppUser = _context.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
            ViewBag.ErrorMessage = "";

            List<Account> accounts = _context.Accounts
                                .Include(a => a.Transactions)
                                .ThenInclude(a => a.Disputes)
                                .Include(a => a.AppUser)
                                .Where(a => a.AppUser.UserName == User.Identity.Name)
                                .ToList();

            if (account.AccountType == AccountType.IRA && accounts.Where(a => a.AccountType == AccountType.IRA).Count() >= 1)
            {
                ViewBag.ErrorMessage = "Each customer may only have one IRA.";
                return View(account);
            }

            if (account.AccountName == null)
            {
                account.AccountName = "Longhorn "+account.AccountType.ToString() +" "+ (accounts.Where(a => a.AccountType == account.AccountType).Count()+1).ToString();
            }
            if (account.AccountType == AccountType.IRA)
            {
                account.Contribution = 0;
            }
            if (ModelState.IsValid)
            {
                account.Active = false;
                _context.Add(account);
                await _context.SaveChangesAsync();

                //Send Email
                String emailSubject = "Welcome to LonghornBank03!";
                String emailBody = @"<div>Hi " + account.AppUser.FirstName + ",</div><br/>";
                emailBody = emailBody + @"<div>Thank you for choosing Longhorn Bank. </div><br/>";
                emailBody = emailBody + @"<div> Your account:</div>" + account.AccountName;
                emailBody = emailBody + @"<div> has been created! Whee!</div><br/>";

                EmailMessaging.SendEmail(account.AppUser.Email, emailSubject, emailBody);
                return RedirectToAction("Transact","Transactions", new { accountID = account.AccountID });
            }

            return View(account);
        }

        // GET: Accounts/Edit/5
        [Authorize(Roles = "Customer")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Accounts == null)
            {
                return View("Error", new string[] { "Please specify an account to edit!" });
            }

            var account = await _context.Accounts.FindAsync(id);

            if (account == null)
            {
                return NotFound();
            }
            if (account.Transactions == null)
            {
                return RedirectToAction("Transact", "Transactions", new { accountID = id });
            }
            if (!account.Active)
            {
                return View("Error", new String[] { "This account is inactivate right now!" });
            }
            return View(account);
        }

        // POST: Accounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Account account)
        {
            if (id != account.AccountID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Account dbAccount = _context.Accounts.Find(account.AccountID);
                    dbAccount.AccountName = account.AccountName;
                    _context.Update(dbAccount);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AccountExists(account.AccountID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details), new { id = id});
            }
            return View(account);
        }

        // GET: Accounts/Inactivate/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Inactivate(int? id)
        {
            if (id == null || _context.Accounts == null)
            {
                return View("Error", new string[] { "Please specify an account to activate/inactivate!" });
            }

            var account = await _context.Accounts
                .Include(a=>a.AppUser)
                .Include(a=>a.Transactions)
                .FirstOrDefaultAsync(m => m.AccountID == id);
            if (account.Active)
            {
                ViewBag.CurrentStatus = "Active";
                ViewBag.StatusChanged = "Inactivate";
            }
            else
            {
                ViewBag.CurrentStatus = "Inactive";
                ViewBag.StatusChanged = "Activate";
            }
            if (account == null)
            {
                return NotFound();
            }

            return View(account);
        }

        // POST: Accounts/Inactivate/5
        [HttpPost, ActionName("Inactivate")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> InactivateConfirmed(int id)
        {
            if (_context.Accounts == null)
            {
                return Problem("Entity set 'AppDbContext.Accounts'  is null.");
            }
            var account = await _context.Accounts.FindAsync(id);
            if (account != null)
            {
                Account dbAccount = _context.Accounts.Find(account.AccountID);

Final_Project/Team3_FinalProject/Controllers/StocksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Team3_FinalProject.DAL;
using Team3_FinalProject.Models;

namespace Team3_FinalProject.Controllers
{
    public class StocksController : Controller
    {
        private readonly AppDbContext _context;

        public StocksController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Stocks
        public async Task<IActionResult> Index()
        {
              return View(await _context.Stocks.ToListAsync());
        }

        // GET: Stocks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Stocks == null)
            {
                return NotFound();
            }

            var stock = await _context.Stocks
                .FirstOrDefaultAsync(m => m.StockID == id);
            if (stock == null)
            {
                return NotFound();
            }

            return View(stock);
        }

        private SelectList GetAllStockTypesSelectList()
        {
            List<StockType> stockTypeList = _context.StockTypes.ToList();

            stockTypeList = _context.StockTypes
                                .Include(s => s.Stocks)
                                .ThenInclude(s => s.StockTransactions)
                                .ToList();

            SelectList stockTypeSelectList = new SelectList(stockTypeList.OrderBy(s => s.StockTypeID), "StockTypeID", "StockTypeName");

            return stockTypeSelectList;
        }

        // GET: Stocks/Create
        public IActionResult Create()
        {
            ViewBag.AllStockTypes = GetAllStockTypesSelectList();
            return View();
        }

        // POST: Stocks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Stock stock, int SelectedStockType)
        {
            if (ModelState.IsValid)
            {
                StockType dbStockType = _context.StockTypes.Find(SelectedStockType);
                stock.StockType = dbStockType;
                _context.Add(stock);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.AllStockTypes = GetAllStockTypesSelectList();
            return View(stock);
        }

        // GET: Stocks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Stocks == null)
            {
                return NotFound();
            }

            var stock = await _context.Stocks.FindAsync(id);
            if (stock == null)
            {
                return NotFound();
            }
            return View(stock);
        }

        // POST: Stocks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StockID,StockName,TickerSymbol,StockPrice")] Stock stock)
        {
            if (id != stock.StockID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(stock);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StockExists(stock.StockID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(stock);
        }

        // GET: Stocks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Stocks == null)
            {
                return NotFound();
            }

            var stock = await _context.Stocks
                .FirstOrDefaultAsync(m => m.StockID == id);
            if (stock == null)
            {
                return NotFound();
            }

            return View(stock);
        }

        // POST: Stocks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Stocks == null)
            {
                return Problem("Entity set 'AppDbContext.Stocks'  is null.");
            }
            var stock = await _context.Stocks.FindAsync(id);
            if (stock != null)
            {
                _context.Stocks.Remove(stock);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StockExists(int id)
        {
          return _context.Stocks.Any(e => e.StockID == id);
        }
    }
}

Final_Project/Team3_FinalProject/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Longhorn Bank & Trust</title>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="nav-content">
                <ul class="navbar-nav mr-auto">
                    @if (User.Identity.IsAuthenticated)
                    {
                        @if (User.IsInRole("Customer"))
                        {


                            <li>
                                <a asp-controller="Accounts" asp-action="Index" class="nav-link">Accounts</a>
                            </li>
                            <li>
                                <a asp-controller="StockPortfolios" asp-action="Index" class="nav-link">Stock Portfolio</a>
                            </li>


                        }
                        @if (User.IsInRole("Employee"))
                        {
                            <li>
                                <a asp-controller="Home" asp-action="StaffHome" class="nav-link">Home</a>
                            </li>
                            <li>
                                <a asp-controller="Accounts" asp-action="Index" class="nav-link">View Accounts</a>
                            </li>
                            <li>
                                <a asp-controller="Transactions" asp-action="Index" class="nav-link">All Transactions</a>
                            </li>
                            <li>
                                <a asp-controller="Account" asp-action="CustomerIndex" class="nav-link">Manage Customers</a>
                            </li>

                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li>
                                <a asp-controller="Home" asp-action="StaffHome" class="nav-link">Home</a>
                            </li>
                            <li>
                                <a asp-controller="Accounts" asp-action="Index" class="nav-link">View Accounts</a>
                            </li>
                            <li>
                                <a asp-controller="Transactions" asp-action="Index" class="nav-link">All Transactions</a>
                            </li>
                            <li>
                                <a asp-controller="Account" asp-action="CustomerIndex" class="nav-link">Manage Customers</a>
                            </li>
                            <li>
                                <a asp-controller="Account" asp-action="EmployeeIndex" class="nav-link">Manage Employees</a>
                            </li>
                            <li>
                                <a asp-controller="Disputes" asp-action="Index" class="nav-link">Disputes</a>
                            </li>
                            <li>
                                <a asp-controller="Stocks" asp-action="Create" class="nav-link">Create Stocks</a>
                            </li>
                        }
                    }
                    else
                    {
                        <li class="nav-item">
                            <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                        </li>
                    }
                </ul>
            </div>
            @await Html.PartialAsync("_LoginPartial")
        </nav>
    </div>

    <div class="container">
        @RenderBody()
    </div>

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/popper.js/popper.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

</body>
</html>