Final_Project/Team3_FinalProject/Models/StockPortfolio.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace Team3_FinalProject.Models
{
    public class StockPortfolio
    {
        public Int32 StockPortfolioID { get; set; }

        // accountNo accountName
        [Display(Name = "Account Number")]
        public UInt32 AccountNo{get;set;}

        [Display(Name = "Account Name")]
        public String AccountName { get; set; }

        [Display(Name = "Cash-Value Portion")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Decimal CashValuePortion { get; set; }

        [Display(Name = "Stock Portion")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Decimal StockPortion { get; set; }

        [Display(Name = "Total Value")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Decimal TotalValue { get; set; }

        public void CalcTotalValue()
        {
            TotalValue = CashValuePortion + StockPortion;
        }

        [Display(Name = "Bonus")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Decimal Bonus { get; set; }

        [Display(Name = "Balanced")]
        public Boolean Balanced { get; set; }

        [Display(Name = "Approved")]
        public Boolean Approved { get; set; }

        public List<StockTransaction> StockTransactions { get; set; }
        public AppUser AppUser { get; set; }

        public StockPortfolio()
        {
            if (StockTransactions == null)
            {
                StockTransactions = new List<StockTransaction>();
            }
        }
    }
}

Final_Project/Team3_FinalProject/Controllers/StockPortfoliosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Security.Principal;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Team3_FinalProject.DAL;
using Team3_FinalProject.Models;

namespace Team3_FinalProject.Controllers
{
    public class StockPortfoliosController : Controller
    {
        private readonly AppDbContext _context;

        public StockPortfoliosController(AppDbContext context)
        {
            _context = context;
        }


        // GET: StockPortfolios
        public async Task<IActionResult> Index()
        {
           
            return View(await _context.StockPortfolios.ToListAsync());
        }

        // GET: StockPortfolios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.StockPortfolios == null)
            {
                return NotFound();
            }

            var stockPortfolio = await _context.StockPortfolios
                .FirstOrDefaultAsync(m => m.StockPortfolioID == id);
            if (stockPortfolio == null)
            {
                return NotFound();
            }

            return View(stockPortfolio);
        }


        // GET: StockPortfolios/Create
        public IActionResult Create()
        {
            return View();
        }




        // POST: StockPortfolios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StockPortfolioID,AccountName,CashValuePortion,StockPortion,TotalValue,Bonus,Balanced,Approved")] StockPortfolio stockPortfolio)
        {

            //assigning the stock options just to the user logged in
            /*if (stockPortfolio.AccountName == null)
            {
                stockPortfolio.AccountName = (stockPortfolio.AppUser.StockPortfolio.Where(a => a.AccountType == stockPortfolio.AccountType).Count() + 1).ToString();
            }

            //ensuring only one stock portfolio account is made
            if (stockPortfolio.AppUser.StockPortfolio.Count(a => a.stockPortfolio == stockPortfolio.StockPortfolioID) = 1)
            {
                ViewBag.ErrorMessage = "Each customer may only have one Stock Portfolio.";
                return View(stockPortfolio);
            }
            */

            if (ModelState.IsValid)
            {
                _context.Add(stockPortfolio);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }
            return View(stockPortfolio);


          
        }
    

    // GET: StockPortfolios/Edit/5
    public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.StockPortfolios == null)
            {
                return NotFound();
            }

            var stockPortfolio = await _context.StockPortfolios.FindAsync(id);
            if (stockPortfolio == null)
            {
                return NotFound();
            }
            return View(stockPortfolio);
        }

        // POST: StockPortfolios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StockPortfolioID,StockPortfolioName,CashValuePortion,StockPortion,TotalValue,Bonus,Balanced,Approved")] StockPortfolio stockPortfolio)
        {
            if (id != stockPortfolio.StockPortfolioID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(stockPortfolio);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StockPortfolioExists(stockPortfolio.StockPortfolioID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(stockPortfolio);
        }

        // GET: StockPortfolios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.StockPortfolios == null)
            {
                return NotFound();
            }

            var stockPortfolio = await _context.StockPortfolios
                .FirstOrDefaultAsync(m => m.StockPortfolioID == id);
            if (stockPortfolio == null)
            {
                return NotFound();
            }

            return View(stockPortfolio);
        }

        // POST: StockPortfolios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.StockPortfolios == null)
            {
                return Problem("Entity set 'AppDbContext.StockPortfolios'  is null.");
            }
            var stockPortfolio = await _context.StockPortfolios.FindAsync(id);
            if (stockPortfolio != null)
            {
                _context.StockPortfolios.Remove(stockPortfolio);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StockPortfolioExists(int id)
        {
          return _context.StockPortfolios.Any(e => e.StockPortfolioID == id);
        }


  

    }
}

Final_Project/Team3_FinalProject/Controllers/StockTransactionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Team3_FinalProject.DAL;
using Team3_FinalProject.Models;

namespace Team3_FinalProject.Controllers
{
    public class StockTransactionsController : Controller
    {
        private readonly AppDbContext _context;

        public StockTransactionsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: StockTransactions
        public async Task<IActionResult> Index()
        {
              return View(await _context.StockTransactions.ToListAsync());
        }

        // GET: StockTransactions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.StockTransactions == null)
            {
                return NotFound();
            }

            var stockTransaction = await _context.StockTransactions
                .FirstOrDefaultAsync(m => m.StockTransactionID == id);
            if (stockTransaction == null)
            {
                return NotFound();
            }

            return View(stockTransaction);
        }

        // GET: StockTransactions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: StockTransactions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StockTransactionID,QuantityShares,SharePrice,Note,StockTXNAmount,StockTXNDate")] StockTransaction stockTransaction)
        {
            if (ModelState.IsValid)
            {
                _context.Add(stockTransaction);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(stockTransaction);
        }

        // GET: StockTransactions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.StockTransactions == null)
            {
                return NotFound();
            }

            var stockTransaction = await _context.StockTransactions.FindAsync(id);
            if (stockTransaction == null)
            {
                return NotFound();
            }
            return View(stockTransaction);
        }

        // POST: StockTransactions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StockTransactionID,QuantityShares,SharePrice,Note,StockTXNAmount,StockTXNDate")] StockTransaction stockTransaction)
        {
            if (id != stockTransaction.StockTransactionID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(stockTransaction);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StockTransactionExists(stockTransaction.StockTransactionID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(stockTransaction);
        }

        // GET: StockTransactions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.StockTransactions == null)
            {
                return NotFound();
            }

            var stockTransaction = await _context.StockTransactions
                .FirstOrDefaultAsync(m => m.StockTransactionID == id);
            if (stockTransaction == null)
            {
                return NotFound();
            }

            return View(stockTransaction);
        }

        // POST: StockTransactions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.StockTransactions == null)
            {
                return Problem("Entity set 'AppDbContext.StockTransactions'  is null.");
            }
            var stockTransaction = await _context.StockTransactions.FindAsync(id);
            if (stockTransaction != null)
            {
                _context.StockTransactions.Remove(stockTransaction);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StockTransactionExists(int id)
        {
          return _context.StockTransactions.Any(e => e.StockTransactionID == id);
        }
    }
}

Final_Project/Team3_FinalProject/Views/StockPortfolios/Create.cshtml
@model Team3_FinalProject.Models.StockPortfolio

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>StockPortfolio</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AccountName" class="control-label"></label>
                <input asp-for="AccountName" class="form-control" />
                <span asp-validation-for="AccountName" class="text-danger"></span>
            </div>
            <!--
                <div class="form-group">
                    <label asp-for="CashValuePortion" class="control-label"></label>
                    <input asp-for="CashValuePortion" class="form-control" />
                    <span asp-validation-for="CashValuePortion" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="StockPortion" class="control-label"></label>
                    <input asp-for="StockPortion" class="form-control" />
                    <span asp-validation-for="StockPortion" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TotalValue" class="control-label"></label>
                    <input asp-for="TotalValue" class="form-control" />
                    <span asp-validation-for="TotalValue" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Bonus" class="control-label"></label>
                    <input asp-for="Bonus" class="form-control" />
                    <span asp-validation-for="Bonus" class="text-danger"></span>
                </div>
                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="Balanced" /> @Html.DisplayNameFor(model => model.Balanced)
                    </label>
                </div>
                -->
                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="Approved" /> @Html.DisplayNameFor(model => model.Approved)
                    </label>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
      
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


Final_Project/Team3_FinalProject/Views/StockPortfolios/Delete.cshtml
@model Team3_FinalProject.Models.StockPortfolio

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StockPortfolio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccountName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccountName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CashValuePortion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CashValuePortion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StockPortion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StockPortion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalValue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalValue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bonus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bonus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Balanced)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Balanced)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Approved)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Approved)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="StockPortfolioID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Final_Project/Team3_FinalProject/Views/StockPortfolios/Details.cshtml
@model Team3_FinalProject.Models.StockPortfolio

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>StockPortfolio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccountName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccountName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CashValuePortion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CashValuePortion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StockPortion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StockPortion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalValue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalValue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bonus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bonus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Balanced)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Balanced)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Approved)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Approved)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.StockPortfolioID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Final_Project/Team3_FinalProject/Views/StockPortfolios/Edit.cshtml
@model Team3_FinalProject.Models.StockPortfolio

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>StockPortfolio</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StockPortfolioID" />
            <div class="form-group">
                <label asp-for="AccountName" class="control-label"></label>
                <input asp-for="AccountName" class="form-control" />
                <span asp-validation-for="AccountName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CashValuePortion" class="control-label"></label>
                <input asp-for="CashValuePortion" class="form-control" />
                <span asp-validation-for="CashValuePortion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockPortion" class="control-label"></label>
                <input asp-for="StockPortion" class="form-control" />
                <span asp-validation-for="StockPortion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalValue" class="control-label"></label>
                <input asp-for="TotalValue" class="form-control" />
                <span asp-validation-for="TotalValue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bonus" class="control-label"></label>
                <input asp-for="Bonus" class="form-control" />
                <span asp-validation-for="Bonus" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Balanced" /> @Html.DisplayNameFor(model => model.Balanced)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Approved" /> @Html.DisplayNameFor(model => model.Approved)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


Final_Project/Team3_FinalProject/Views/StockPortfolios/Index.cshtml
@model IEnumerable<Team3_FinalProject.Models.StockPortfolio>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AccountName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CashValuePortion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StockPortion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalValue)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bonus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Balanced)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Approved)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AccountName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CashValuePortion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StockPortion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalValue)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bonus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Balanced)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Approved)
            </td>
            <td>

                <a asp-action="Details" asp-route-id="@item.StockPortfolioID">Details</a>
                <a asp-action="Index" asp-controller="StockTransactions" class="btn btn-info">Stock Transaction</a>

            </td>
        </tr>
}
    </tbody>
</table>